# Generated by Django 2.2.6 on 2019-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_remove_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
