# Generated by Django 2.2.6 on 2019-11-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20191031_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
