# Generated by Django 2.2.6 on 2019-11-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='categories')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
