# Generated by Django 2.2.6 on 2019-10-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191030_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
