# Generated by Django 2.2.6 on 2019-10-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
