# Generated by Django 2.2.6 on 2019-10-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
