# Generated by Django 2.2.6 on 2019-11-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0010_auto_20191101_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=100)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post')),
            ],
        ),
    ]
