# Generated by Django 2.2.6 on 2019-11-02 05:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('singlepost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 2, 5, 37, 3, 169336, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, max_length=100)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='singlepost.Comment')),
            ],
        ),
    ]
