# Generated by Django 2.2.6 on 2019-11-02 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('singlepost', '0002_auto_20191102_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 2, 6, 14, 10, 569441, tzinfo=utc)),
        ),
    ]
