# Generated by Django 2.2.6 on 2019-11-02 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('singlepost', '0004_auto_20191102_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 2, 13, 43, 0, 95649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singlepost.Comment'),
        ),
    ]
